In [1]:
import numpy as np
import neural_network_library as nnl

# Created XOR Dataset

In [2]:
np.random.seed(42)

# Define the xor dataset
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1],
], dtype = np.float32)

y = np.array([
    [0],
    [1],
    [1],
    [0],
], dtype= np.float32)

# Define Sigmoid and Tanh Models

In [4]:
# Define the model
model_sigmoid = nnl.Sequential(
    layers=[
        nnl.Linear(input_size = 2, output_size=2),
        nnl.Sigmoid(),
        nnl.Linear(input_size = 2, output_size = 1),
        nnl.Sigmoid()
    ]
)

model_tanh = nnl.Sequential(
    layers=[
        nnl.Linear(input_size = 2, output_size=2),
        nnl.Tanh(),
        nnl.Linear(input_size = 2, output_size = 1),
        nnl.Sigmoid()
    ]
)

# Define the loss function
loss_sig_fn = nnl.BceLoss()
loss_tanh_fn = nnl.BceLoss()
learning_rate_sigmoid = 1
learning_rate_tanh = 0.5
n_epochs = 100000

# Train Sigmoid and Tanh Models

In [6]:
# Train the model_sigmoid
for epoch in range(n_epochs):
    # Forward pass
    y_pred_sig = model_sigmoid.forward(X)
    loss_sig = loss_sig_fn.forward(y_pred_sig, y)
    
    # Backward pass
    grad_sig = loss_sig_fn.backward()
    model_sigmoid.backward(grad_sig)

    # Update the weights
    for layer in model_sigmoid.layers:
        if isinstance(layer, nnl.Linear):
            layer.weights -= learning_rate_sigmoid * layer.grad_weights
            layer.bias -= learning_rate_sigmoid * layer.grad_bias
    
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Sigmoid loss: {loss_sig}")

Epoch 0, Sigmoid loss: 0.008210874906870648
Epoch 1000, Sigmoid loss: 0.008154491371567426
Epoch 2000, Sigmoid loss: 0.0080992344765236
Epoch 3000, Sigmoid loss: 0.00804506741273565
Epoch 4000, Sigmoid loss: 0.007991955027828394
Epoch 5000, Sigmoid loss: 0.007939863731605452
Epoch 6000, Sigmoid loss: 0.007888761408089633
Epoch 7000, Sigmoid loss: 0.0078386173335329
Epoch 8000, Sigmoid loss: 0.007789402099922982
Epoch 9000, Sigmoid loss: 0.007741087543558867
Epoch 10000, Sigmoid loss: 0.007693646678300843
Epoch 11000, Sigmoid loss: 0.0076470536331398
Epoch 12000, Sigmoid loss: 0.007601283593759364
Epoch 13000, Sigmoid loss: 0.007556312747792285
Epoch 14000, Sigmoid loss: 0.007512118233499147
Epoch 15000, Sigmoid loss: 0.00746867809161979
Epoch 16000, Sigmoid loss: 0.00742597122016713
Epoch 17000, Sigmoid loss: 0.007383977331955161
Epoch 18000, Sigmoid loss: 0.007342676914667201
Epoch 19000, Sigmoid loss: 0.007302051193286738
Epoch 20000, Sigmoid loss: 0.007262082094727958
Epoch 21000, S

In [7]:
# Train the model_tanh
for epoch in range(n_epochs):
    # Forward pass
    y_pred_tanh = model_tanh.forward(X)
    loss_tanh = loss_tanh_fn.forward(y_pred_tanh, y)
    
    # Backward pass
    grad_tanh = loss_tanh_fn.backward()
    model_tanh.backward(grad_tanh)

    # Update the weights
    for layer in model_tanh.layers:
        if isinstance(layer, nnl.Linear):
            layer.weights -= learning_rate_tanh * layer.grad_weights
            layer.bias -= learning_rate_tanh * layer.grad_bias
    
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Tanh loss: {loss_tanh}")

Epoch 0, Tanh loss: 0.005703635132524896
Epoch 1000, Tanh loss: 0.005673685660181101
Epoch 2000, Tanh loss: 0.0056441981965530625
Epoch 3000, Tanh loss: 0.005615161027623237
Epoch 4000, Tanh loss: 0.005586562850175891
Epoch 5000, Tanh loss: 0.005558392753482828
Epoch 6000, Tanh loss: 0.005530640201974483
Epoch 7000, Tanh loss: 0.0055032950188380215
Epoch 8000, Tanh loss: 0.0054763473704815945
Epoch 9000, Tanh loss: 0.0054497877518124935
Epoch 10000, Tanh loss: 0.0054236069722792815
Epoch 11000, Tanh loss: 0.005397796142631145
Epoch 12000, Tanh loss: 0.005372346662351819
Epoch 13000, Tanh loss: 0.0053472502077272785
Epoch 14000, Tanh loss: 0.0053224987205107745
Epoch 15000, Tanh loss: 0.005298084397148144
Epoch 16000, Tanh loss: 0.005273999678534226
Epoch 17000, Tanh loss: 0.005250237240266549
Epoch 18000, Tanh loss: 0.005226789983369768
Epoch 19000, Tanh loss: 0.005203651025464185
Epoch 20000, Tanh loss: 0.005180813692352786
Epoch 21000, Tanh loss: 0.0051582715100036754
Epoch 22000, Ta

# Predictions

In [8]:
print("\nPredictions after training for sigmoid:")
print(np.round(model_sigmoid.forward(X), 3))
model_sigmoid.save(r"Models\xor_model_sigmoid.npz")
print('weights sigmoid:', model_sigmoid.layers[0].weights)



Predictions after training for sigmoid:
[[0.005]
 [0.995]
 [0.995]
 [0.006]]
weights sigmoid: [[-6.92366536 -6.92071224]
 [-5.56788894 -5.56722558]]


In [9]:
print("\nPredictions after training for tanh:")
print(np.round(model_tanh.forward(X), 3))
model_tanh.save(r"Models\xor_model_tanh.npz")
print('weights tanh:', model_tanh.layers[0].weights)



Predictions after training for tanh:
[[0.005]
 [0.997]
 [0.997]
 [0.005]]
weights tanh: [[-3.81333813 -3.80589103]
 [ 2.96233241  2.9606089 ]]


In [10]:
print("\nGround truth:")
print(y)


Ground truth:
[[0.]
 [1.]
 [1.]
 [0.]]
